### ISSUE TITLE
Unable to upload PDF files to NetBout

### ISSUE THREAD

**Issue by super132** [yegor256/netbout#703]
When I start a new bout and click on files button to upload a file, say a PDF with size below 1MB. Server responds "bad request". However, I can upload a text file without problem.

**Comment by dmzaytsev** [comment]
@super132 thanks for reporting

**Comment by dmzaytsev** [comment]
@karato it's valid bug

**Comment by karato** [comment]
> @karato it's valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@super132 milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@super132 thanks for this report, I added 15 mins to your account, in transaction `AP-64Y640539S5374243`

**Comment by dmzaytsev** [comment]
@karato assign this to @antonini please

**Comment by karato** [comment]
> @karato assign this to @antonini please

@dmzaytsev done. @antonini you are assigned to this task. please proceed...

**Comment by antonini** [comment]
@dmzaytsev Do you know if it's possible to upload files when running netbout locally? I have a situation on my environment that I don't know if it is something that I can't do or is a problem.

Here it is what is happening:
In a local instance, when I try to upload a pdf, it invokes a mock class of Bucket. That mock doesn't do anything with the file content. So, when I try to download the file, it is blank.

**Comment by dmzaytsev** [comment]
@antonini Netbout uses Amazon S3 as a storage for attachments. It should work locally using a mocked objects from https://github.com/jcabi/jcabi-s3. 
I don't know... maybe it's a bug in your code or maybe it's a bug in jcabi-s3...
If second feel free to submit a bug into jcabi-s3 project

**Comment by antonini** [comment]
@karato PR #747 ready for review.

**Comment by karato** [comment]
> @karato PR #747 ready for review.

@antonini OK, thanks, will take a look soon

**Comment by antonini** [comment]
@karato Need more time, think this is a problem inside takes project.

**Comment by karato** [comment]
> @karato Need more time, think this is a problem inside takes project.

@antonini sure, take your time

**Comment by antonini** [comment]
@karato This issue depends on resolution of issue [takes/#372](https://github.com/yegor256/takes/issues/372).

**Comment by karato** [comment]
> @karato This issue depends on resolution of issue [takes/#372](https://github.com/yegor256/takes/issues/372).

@antonini @karato more time

**Comment by karato** [comment]
@super132 there is a puzzle in this code `703-ca5668ad`/#753, we'll resolve it later

**Comment by antonini** [comment]
@karato As this issue depends on a third party fix, I think the amount of "spend time" inside netbout should stop.

**Comment by karato** [comment]
> @karato As this issue depends on a third party fix, I think the amount of "spend time" inside netbout should stop.

@antonini I'm not sure I understood you... what exactly do you mean?

**Comment by antonini** [comment]
@karato This issue is on hold because an error that is going to be fixed on Takes project. I saw inside netbout that the spent time of this issue continues to grow. Is it correct?

**Comment by yegor256** [comment]
@karato pls add extra 30 minutes to @antonini (for #564)

**Comment by karato** [comment]
> @karato pls add extra 30 minutes to @antonini (for #564)

@yegor256 I've sent 30 mins extra to @antonini in transaction ID "AP-7F427171HF068030E"

**Comment by antonini** [comment]
@super132 Takes project was fixed and updated. Can you teste it?

**Comment by super132** [comment]
@antonini Just have a test in production netbout. I uploaded a PDF file with size 7kb and I can upload it without problem. However, when I try uploading a PDF with size 569kb, I got bad request again. Thanks.

**Comment by antonini** [comment]
@super132 Strange. I just uploaded this file and it worked fine. http://nvie.com/files/Git-branching-model.pdf.

**Comment by antonini** [comment]
@super132 Can you close it?

**Comment by super132** [comment]
@antonini Sorry but I cannot close the request as I still experience "bad request" error when uploading a PDF file like the one below in production:

https://ptgmedia.pearsoncmg.com/images/9780735619654/samplepages/9780735619654.pdf

Not sure why but it does happen. Thanks.

**Comment by karato** [comment]
@super132 last puzzled solved `703-ca5668ad`/#753
