### ISSUE TITLE
2.19

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#815]
Please, publish a new release **2.19** (or higher). Don't forget to update us here regularly (at least once a week), as explained in [this article](http://www.yegor256.com/2015/05/11/software-architect-responsibilities.html).

**Comment by karato** [comment]
@dmzaytsev this is your task

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev there are some issues in the project now:

 * some tasks are stuck: #737 (99 days), #738 (98 days), #750 (83 days), #756 (69 days), #754 (69 days), #755 (69 days), #761 (61 days), #758 (61 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #809, #808, #807, #796. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1). Please, do something about it.

added -25 to your rating, now it is equal to [+1422](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev the bonus here is 1 hour and 29 mins, due to these numbers: t=0, c=1, h=435, diff=2.18..master, [this page](http://www.teamed.io/release.html) explains the formula

**Comment by dmzaytsev** [comment]
@yegor256 I'm going to release `2.19` with new Takes if you don't mind

**Comment by yegor256** [comment]
@dmzaytsev go ahead

**Comment by dmzaytsev** [comment]
@rultor release, tag='2.19'

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.19`

**Comment by karato** [comment]
@dmzaytsev there are a few issues:

 * some tasks are stuck: #737 (104 days), #738 (103 days), #750 (88 days), #756 (74 days), #754 (74 days), #761 (66 days), #758 (66 days), #767 (63 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #809, #808, #807, #796. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1). Please, either close them or update due dates.

-25 added to your rating, at the moment it is: [+1488](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment]
@yegor256 Facebook login issue has been fixed, I'm going to release `2.20`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.20`

**Comment by dmzaytsev** [comment]
@yegor256 it works

**Comment by yegor256** [comment]
@dmzaytsev cool, thanks

**Comment by karato** [comment]
@dmzaytsev pay attention to the following:

 * some tasks are stuck: #737 (107 days), #738 (106 days), #750 (91 days), #756 (78 days), #754 (78 days), #761 (69 days), #758 (69 days), #767 (66 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * these issues are still not dispatched anyhow: #796. Either register as bugs or ask their reporters to close.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1). Please, do something about it.

-25 added to your rating, current score is: [+1448](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev there are a few issues:

 * some tasks are stuck: #737 (110 days), #738 (110 days), #750 (95 days), #756 (81 days), #754 (81 days), #761 (73 days), #758 (73 days), #767 (69 days); please do something about it. There are basically three options: 1) mark some of them as "postponed" (see [par.26](http://www.teamed.io/policy.html#26)), 2) re-assign them (see [par.29](http://www.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #796. Either register as bugs or ask their reporters to close.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1). Please, do something about it.

-25 added to your rating, at the moment it is: [+1448](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev There are a few problems in the project now:

 * some tasks are stuck: #737 (114 days), #738 (113 days), #750 (98 days), #756 (84 days), #754 (84 days), #761 (76 days), #758 (76 days), #767 (72 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * these issues are still not dispatched anyhow: #796. Either register as bugs or ask their reporters to close.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1). Please, do something about it.

-25 to your rating, your total score is [+1442](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.21`

**Comment by dmzaytsev** [comment]
@yegor256 would it possible make 2.21 final?

**Comment by yegor256** [comment]
@karato release 2.21 is final

**Comment by karato** [comment]
> @karato release 2.21 is final

@yegor256 it is final now (2.21 doesn't have "draft" flag any more)

**Comment by karato** [comment]
@dmzaytsev there are some issues (see [par.33](http://www.teamed.io/policy.html#33)) in the project now:

 * some tasks are stuck: #737 (121 days), #738 (121 days), #750 (106 days), #756 (92 days), #754 (92 days), #761 (84 days), #758 (84 days), #767 (80 days); please do something about it. There are basically three options: 1) mark some of them as "postponed" (see [par.26](http://www.teamed.io/policy.html#26)), 2) re-assign them (see [par.29](http://www.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #796. Either register as bugs or ask their reporters to close.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1). Please, do something about it.

-25 added to your rating, current score is: [+1350](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev Finished, thanks, closing..

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **30 mins** was added to your account, payment ID is `69587376`, 656 hours and 15 mins spent total

+30 added to your rating, current score is: [+1311](http://www.netbout.com/b/35166?open=rating)
